-- CONFIGURANDO  EL DATAFILE 
CREATE TABLESPACE TB_APP_FLYER DATAFILE 'C:\Tablespaces\app_flyers\TB_APP_FLYER_01.DBF' SIZE 10M
AUTOEXTEND ON
NEXT 10M 
MAXSIZE 250M;

-- CREANDO EL USUARIO ROOT
CREATE USER APP_FLYER IDENTIFIED BY APP_FLYER 
DEFAULT TABLESPACE TB_APP_FLYER;
-- CREANDO EL USUARIO DE LA APP
CREATE USER USER_FLYER IDENTIFIED BY USER_FLYER
DEFAULT TABLESPACE TB_APP_FLYER;
--  PERMISOS USUARIOS ROOT 
GRANT RESOURCE, CONNECT TO APP_FLYER;
-- AGREGANDO QUOTA
ALTER USER APP_FLYER QUOTA 10M ON TB_APP_FLYER;

-- CONFIGURANDO DIRECTORIO PARA GUARDAR LOS FLYERS
CREATE DIRECTORY APP_FLYERS AS 'C:\directory_oracle\app_flyer';
GRANT READ, WRITE ON DIRECTORY APP_FLYERS TO APP_FLYER;

-- CONFIGURANDO DIRECTORIO PARA GUARDAR LOS ADJUNTOS
CREATE DIRECTORY APP_FLYER_ADJUNTO AS 'C:\directory_oracle\app_flyer\ADJUNTOS';
GRANT READ,WRITE ON DIRECTORY APP_FLYER_ADJUNTO TO APP_FLYER;