-- TABLAS PRIMARIAS
CREATE TABLE APP_FLYER.TA_TIPO_ADJU
(
  ID_TIPO_ADJU CHAR(5) PRIMARY KEY,
  NO_TIPO_ADJU VARCHAR2(20) UNIQUE NOT NULL,
  CO_USER_APP INTEGER NOT NULL,
  ES_TIPO_ADJU CHAR(1) DEFAULT 'A' NOT NULL,
  DA_IP_TIPO_ADJU CHAR(15) DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS') NOT NULL,
  DA_DESKTOP_TIPO_ADJU VARCHAR2(15) DEFAULT SYS_CONTEXT('USERENV','HOST') NOT NULL,
  FE_CREA_TIPO_ADJU DATE DEFAULT SYSDATE NOT NULL
);
COMMENT ON TABLE APP_FLYER.TA_TIPO_ADJU IS 'Tabla primaria para guardar los tipos adjuntos.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.ID_TIPO_ADJU IS 'Codigo del tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.NO_TIPO_ADJU IS 'Nombre del tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.ES_TIPO_ADJU IS 'Estado del tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.CO_USER_APP IS 'Codigo del usuario que grabo el nuevo tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.DA_IP_TIPO_ADJU IS 'Ip de la maquina que grabo el nuevo tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.DA_DESKTOP_TIPO_ADJU IS 'PC que se utilizo para grabar el nuevo tipo de adjunto.';
COMMENT ON COLUMN APP_FLYER.TA_TIPO_ADJU.FE_CREA_TIPO_ADJU IS 'Fecha que se subio el nuevo tipo de adjunto.';

CREATE TABLE APP_FLYER.TP_FLYER
(
  ID_FLYER CHAR(5) PRIMARY KEY,
  NO_FLYER VARCHAR2(20) UNIQUE NOT NULL,
  IG_FLYER BFILE NOT NULL,
  CO_USER_APP INTEGER NOT NULL,
  DA_IP_USER_FLYER CHAR(15) DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS') NOT NULL,
  DA_DESKTOP_USER_FLYER VARCHAR2(15) DEFAULT SYS_CONTEXT('USERENV','HOST') NOT NULL,
  FE_CREA_FLYER DATE DEFAULT SYSDATE NOT NULL,
  ES_FLYER CHAR(1) DEFAULT 'A' NOT NULL
);
ALTER TABLE APP_FLYER.TP_FLYER MODIFY NO_FLYER VARCHAR2(50);

COMMENT ON TABLE APP_FLYER.TP_FLYER IS 'Tabla primaria para guardar los datos y imagen del flyer';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.ID_FLYER IS 'Codigo del flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.NO_FLYER IS 'Nombre del flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.IG_FLYER IS 'Ruta del directorio de la imagen del flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.CO_USER_APP IS 'Usuario que guardo el flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.DA_IP_USER_FLYER IS 'Ip de la maquina donde se subio el flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.DA_DESKTOP_USER_FLYER IS 'Nombre de la Pc donde se subio el flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.FE_CREA_FLYER IS 'Fecha donde se subio el flyer.';
COMMENT ON COLUMN APP_FLYER.TP_FLYER.ES_FLYER IS 'Estado del flyer';

-- TABLA DE ERROR APP_ FLYER
CREATE TABLE APP_FLYER.TP_ERROR_APP(
  ID_ERROR_APP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NO_ERROR_APP VARCHAR2(50),
  NO_OBJT_ERROR_APP VARCHAR2(50),
  CO_ERROR_APP INTEGER,
  DA_MSG_ERROR_APP VARCHAR2(1000),
  DA_ERROR_APP CLOB,
  FE_CREA_ERROR_APP TIMESTAMP DEFAULT SYSDATE,
  CO_USER_ERROR_APP INTEGER,
  DA_IP_ERROR_APP CHAR(15) DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS'),
  DA_DESKTOP_APP  VARCHAR2(30) DEFAULT SYS_CONTEXT('USERENV','HOST')  
);
COMMENT ON TABLE APP_FLYER.TP_ERROR_APP IS 'Tabla principal que almacena los errores de las aplicaciones';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.ID_ERROR_APP IS 'Codigo del error de la aplicacion.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.NO_ERROR_APP IS 'Nombre de la aplicacion que genero el error.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.NO_OBJT_ERROR_APP IS 'Nombre del objeto que genero el error.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.CO_ERROR_APP IS 'SQLCODE que se ha obtenido de la session.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.DA_MSG_ERROR_APP IS 'SQLERRM que se ha obtendio de la session.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.DA_ERROR_APP IS 'Descripcion detallada del error obtenido';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.FE_CREA_ERROR_APP IS 'Fecha de creacion del error.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.CO_USER_ERROR_APP IS 'Usuario que genero el error.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.DA_IP_ERROR_APP IS 'Ip donde se genero el error.';
COMMENT ON COLUMN APP_FLYER.TP_ERROR_APP.DA_DESKTOP_APP IS 'Nombre de la pc que genero el error.';


-- TABLAS SECUNDARIAS

CREATE TABLE APP_FLYER.TP_ADJU 
(
  ID_ADJU CHAR(5) PRIMARY KEY, 
  NO_ADJU VARCHAR2(30) UNIQUE NOT NULL,
  DO_AJU BFILE,
  URL_ADJU VARCHAR2(500),
  CO_USER_APP INTEGER NOT NULL,
  DA_IP_USER_ADJU CHAR(15) DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS') NOT NULL,
  DA_DESKTOP_USER_ADJU VARCHAR2(15) DEFAULT SYS_CONTEXT('USERENV','HOST') NOT NULL,
  FE_CREA_ADJU DATE DEFAULT SYSDATE NOT NULL,
  ES_ADJU CHAR(1) DEFAULT 'A' NOT NULL,
  ID_TIPO_ADJU CHAR(5) NOT NULL,
  ID_FLYER CHAR(5) NOT NULL,
  CONSTRAINT FK_TP_ADJU_TIPO_ADJU FOREIGN KEY(ID_TIPO_ADJU) REFERENCES APP_FLYER.TA_TIPO_ADJU(ID_TIPO_ADJU),
  CONSTRAINT FK_TP_ADJU_TP_FLYER FOREIGN KEY(ID_FLYER) REFERENCES APP_FLYER.TP_FLYER(ID_FLYER)
);

ALTER TABLE APP_FLYER.TP_ADJU
RENAME COLUMN DO_AJU TO DO_ADJU;

COMMENT ON TABLE APP_FLYER.TP_ADJU IS 'Tabla Foreign para los adjuntos del flyer.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.ID_ADJU IS 'Codigo del adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.NO_ADJU IS 'Nombre del adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.DO_ADJU IS 'Ruta del pdf,word,excel del adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.URL_ADJU IS 'Url del google drive del adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.CO_USER_APP IS 'Usuario que subio el adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.DA_IP_USER_ADJU IS 'Ip de la maquina que subio el adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.DA_DESKTOP_USER_ADJU IS 'Pc donde se subio el adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.ES_ADJU IS 'Estado del adjunto.';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.ID_TIPO_ADJU IS 'Codigo del tipo de adjunto, relacionado con la tabla ta_tipo_adju';
COMMENT ON COLUMN APP_FLYER.TP_ADJU.ID_FLYER IS 'Codigo del flyer relacionado con la tabla tp_flyer.';

-- SEQUENCIALES
CREATE SEQUENCE SEQ_TA_TIPO_ADJU 
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_TP_FLYER
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_TP_ADJU
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- CREAMOS EL OBJETOS
CREATE OR REPLACE TYPE TOBJ_FLYER AS OBJECT(
  ID_FLYER CHAR(5),
  NO_FLYER VARCHAR2(50),
  IG_FLYER BLOB
);
/
CREATE OR REPLACE TYPE TA_FLYER AS TABLE OF TOBJ_FLYER;
/

-- CREAMOS OBJETOS PARA DEVOLVER LOS ADJUNTOS
CREATE OR REPLACE TYPE TOBJ_ADJU AS OBJECT (
  ID_ADJU CHAR(5),
  NO_ADJU VARCHAR2(50),
  DO_ADJU BLOB,
  URL_ADJU VARCHAR2(1000),
  ID_TIPO_ADJU CHAR(5),
  ID_FLYER CHAR(5)
);

CREATE OR REPLACE TYPE TA_ADJU AS TABLE OF TOBJ_ADJU;
