-- INSERT EN LA TABLA TP_TIPO_ADJU
INSERT INTO APP_FLYER.TA_TIPO_ADJU
(ID_TIPO_ADJU,NO_TIPO_ADJU,ES_TIPO_ADJU)
VALUES
(LPAD(SEQ_TA_TIPO_ADJU.NEXTVAL,5,'0'),'PDF','A');

INSERT INTO APP_FLYER.TA_TIPO_ADJU
(ID_TIPO_ADJU,NO_TIPO_ADJU,ES_TIPO_ADJU)
VALUES
(LPAD(SEQ_TA_TIPO_ADJU.NEXTVAL,5,'0'),'URL DRIVE','A');

INSERT INTO APP_FLYER.TA_TIPO_ADJU
(ID_TIPO_ADJU,NO_TIPO_ADJU,ES_TIPO_ADJU)
VALUES
(LPAD(SEQ_TA_TIPO_ADJU.NEXTVAL,5,'0'),'EXCEL','A');

INSERT INTO APP_FLYER.TA_TIPO_ADJU
(ID_TIPO_ADJU,NO_TIPO_ADJU,ES_TIPO_ADJU)
VALUES
(LPAD(SEQ_TA_TIPO_ADJU.NEXTVAL,5,'0'),'WORD','A');

COMMIT;
