CREATE OR REPLACE TRIGGER TR_AUDIT_TP_FLYER_01 
AFTER INSERT OR UPDATE OR DELETE ON APP_FLYER.TP_FLYER
FOR EACH ROW 
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
 IF INSERTING THEN
   INSERT INTO APP_FLYER.AUDIT_TP_FLYER
    (TI_OPER,
    ID_FLYER,
    NO_FLYER,
    IG_FLYER,
    DA_CO_USER_AUTH_APP_CREA,
    DA_IP_USER_CREA,
    DA_DESKTOP_USER_CREA,
    FE_CREA_FLYER)
    VALUES
    ('I',
     :NEW.ID_FLYER,
     :NEW.NO_FLYER,
     BFILENAME('APP_FLYERS',:NEW.NO_FLYER),
     NVL(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),0),
     SYS_CONTEXT('USERENV','IP_ADDRESS'),
     SYS_CONTEXT('USERENV','HOST'),
     SYSTIMESTAMP);
 END IF;
 IF UPDATING THEN
    INSERT INTO APP_FLYER.AUDIT_TP_FLYER
    (TI_OPER,
    ID_FLYER,
    NO_FLYER,
    IG_FLYER,
    DA_CO_USER_AUTH_APP_MODI,
    DA_IP_USER_MODI,
    DA_DESKTOP_USER_MODI,
    FE_MODI_FLYER)
    VALUES
    ('U',
     :OLD.ID_FLYER,
     :OLD.NO_FLYER,
     BFILENAME('APP_FLYERS',:OLD.NO_FLYER),
     NVL(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),0),
     SYS_CONTEXT('USERENV','IP_ADDRESS'),
     SYS_CONTEXT('USERENV','HOST'),
     SYSTIMESTAMP);
 END IF;
 IF DELETING THEN
    INSERT INTO  APP_FLYER.AUDIT_TP_FLYER
    (TI_OPER,
    ID_FLYER,
    NO_FLYER,
    IG_FLYER,
    DA_CO_USER_AUTH_APP_MODI,
    DA_IP_USER_MODI,
    DA_DESKTOP_USER_MODI,
    FE_MODI_FLYER)
    VALUES
    ('D',
     :OLD.ID_FLYER,
     :OLD.NO_FLYER,
     BFILENAME('APP_FLYERS',:OLD.NO_FLYER),
     NVL(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),0),
     SYS_CONTEXT('USERENV','IP_ADDRESS'),
     SYS_CONTEXT('USERENV','HOST'),
     SYSTIMESTAMP);
 END IF;
 COMMIT;
EXCEPTION 
   WHEN OTHERS THEN
      APP_FLYER.PKG_DAO_APP_FLYER.INS_ERROR_LOG(APP_FLYER.PKG_UTIL.NO_APP,NVL(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),0));
END;
/

